Game turn
Malamdg/TipeEnzo pull request #6
Opened 2024-05-29 08:11 UTC by ZO0ne

Completed get_available_roads, added get_affordable_roads.
Added show_cards_from_hand in order to be able to show to the player a part or all of the train cards in his hand.
 Added get_usable_card_indices in order to get the list of the indices of the cards from the player hand the player can use to pay and occupy the road.
 Added discard_cards, added pay_road_cost which allow the player to choose which card from the usable ones, he wish to use in order to pay the price of occupying the road.
 Completed place_train_pawn .

2024-05-29 14:10 UTC, Malamdg requested changes

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +            chosen_cards_indices.append(int(input(f"Which card do you wish to use ? \n"
controle la valeur, et si l'utilisateur fait une faute de frappe? comment tu espère que le code va gérer ?

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +        hand = self.cards.count_by_color()
et le joker ?

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +                if sum(Hand.values()):
c'est quoi Hand ? et la condition ne semble pas complète

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +    def get_usable_card_indices(self, color_cost):
tu peux ajouter le type pour color_cost

indexes et pas indices

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +        usable_card_indices = []
idem

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +        c = 0
un nom qui a du sens et qui dit ce qu'est la variable, ou un nom normé comme n ou i

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +    def show_cards_from_hand(self, indices):
indexes et pas indices
où est le type ?

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +        for i in indices:
index pas i dcp

2024-05-29 14:10 UTC, Malamdg commented on src/Players.py
> +                    affordable_roads.append(road)
tu vois que tu répète l'instruction ici, il est possible de factoriser ton code en
- changeant tes if imbriqués pour les conditions opposées et mettre un continue
- retirant le else mais en gardant le if imbriqué à l'intérieur

2024-05-29 14:15 UTC, Malamdg requested changes
Il y a beaucoup de retours, n'ai pas peur lis les tous puis prend les un par un et fait
un commit par fonction. Il faut aussi que tu change ton message en mettant avec 
du français et pas des noms de fonctions les changements effectués. 

Si tu n'es pas sûr de comprendre ce que j'ai voulu dire dans un de mes retours réponds y un commentaire. 

C'est moi qui resolve les threads pas toi.

Il faut aussi que tu t'assignes à la PR.

2024-05-30 05:15 UTC, ZO0ne commented on src/GameEntities/Cards.py
> +    def count_by_color(self):
réglé

2024-05-30 05:16 UTC, ZO0ne commented on src/Players.py
> +            drawn_card = input(f"Which one do you choose ?")
non mais réglé

2024-05-30 05:16 UTC, ZO0ne commented on src/Players.py
> +                drawn_card = input(f"Which one do you choose ?")
réglé

2024-05-30 05:16 UTC, ZO0ne commented on src/Players.py
> +        usable_card_indices = []
réglé

2024-05-30 05:23 UTC, ZO0ne commented on src/Players.py
> +        c = 0
c'est bon

2024-05-30 05:23 UTC, ZO0ne commented on src/Players.py
> +    def show_cards_from_hand(self, indices):
fait

2024-05-30 05:26 UTC, ZO0ne commented on src/Players.py
> +        for i in indices:
oui

2024-06-06 19:22 UTC, merged